export const projectTemplates = [
  {
    id: "1",
    title: "E-commerce React",
    description: "Template completo de e-commerce com React e Firebase",
    tech: ["React", "Firebase", "Stripe"],
    difficulty: "Avançado",
    stars: 1250,
    downloads: "5.2k",
    requirements: ["Node.js v16+", "Firebase Account", "Stripe Account"],
  },
  {
    id: "2",
    title: "Dashboard Admin Vue",
    description: "Template de dashboard administrativo com Vue.js e Tailwind CSS",
    tech: ["Vue.js", "Tailwind CSS", "Chart.js"],
    difficulty: "Intermediário",
    stars: 890,
    downloads: "3.8k",
    requirements: ["Node.js v16+", "Vue CLI"],
  },
  {
    id: "3",
    title: "API REST Node.js",
    description: "Template de API REST com Node.js, Express e MongoDB",
    tech: ["Node.js", "Express", "MongoDB"],
    difficulty: "Intermediário",
    stars: 650,
    downloads: "2.5k",
    requirements: ["Node.js v16+", "MongoDB Atlas Account"],
  },
]