version: '3.8'

services:
  # Backend API
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
      target: runner
    image: 10xdev-backend
    container_name: 10xdev_backend
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production
      - PORT=3001
      - SUPABASE_URL=${SUPABASE_URL}
      - SUPABASE_ANON_KEY=${SUPABASE_ANON_KEY}
      - SUPABASE_SERVICE_ROLE_KEY=${SUPABASE_SERVICE_ROLE_KEY}
    volumes:
      - 10xdev_app_data:/app/logs
      - 10xdev_node_cache:/app/node_modules/.cache
    networks:
      - 10xdev_network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "sh", "-c", "wget --no-verbose --tries=1 --spider http://localhost:3001/ || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Frontend Next.js
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      target: runner
    image: 10xdev-front
    container_name: 10xdev_frontend
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
      - NEXT_PUBLIC_API_URL=http://backend:3001/api
    volumes:
      - 10xdev_node_cache:/app/.next/cache
    networks:
      - 10xdev_network
    depends_on:
      - backend
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "sh", "-c", "wget --no-verbose --tries=1 --spider http://localhost:3000/ || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  10xdev_network:
    driver: bridge

volumes:
  10xdev_app_data:
    external: true
  10xdev_node_cache:
    external: true