export const videoLessons = [
  {
    id: "1",
    title: "Introdução ao React",
    description: "Conceitos básicos e setup do ambiente",
    duration: "30min",
    chapter: 1,
    completed: true,
    track: "React Fundamentals",
  },
  {
    id: "2",
    title: "Componentes e Props",
    description: "Aprenda a criar componentes reutilizáveis",
    duration: "45min",
    chapter: 2,
    completed: true,
    track: "React Fundamentals",
  },
  {
    id: "3",
    title: "Estado e Eventos",
    description: "Gerenciamento de estado e manipulação de eventos",
    duration: "60min",
    chapter: 3,
    completed: false,
    track: "React Fundamentals",
  },
  {
    id: "4",
    title: "Hooks em React",
    description: "Aprenda a usar hooks para gerenciar o estado e o ciclo de vida",
    duration: "75min",
    chapter: 1,
    completed: false,
    track: "React Avançado",
  },
  {
    id: "5",
    title: "Context API",
    description: "Compartilhamento de estado entre componentes",
    duration: "90min",
    chapter: 2,
    completed: false,
    track: "React Avançado",
  },
]