import { Request, Response, NextFunction } from 'express'
import { SupabaseAuthAdapter } from '../adapters/SupabaseAuthAdapter'

const adapter = new SupabaseAuthAdapter()

/**
 * Middleware to validate JWT tokens and populate req.user
 * Works with custom JWT tokens generated by SupabaseAuthAdapter
 */
export async function supabaseMiddleware(
  req: Request,
  res: Response,
  next: NextFunction
): Promise<any> {
  try {
    const authHeader = req.headers.authorization

    if (!authHeader || !authHeader.startsWith('Bearer ')) {
      return res.status(401).json({
        error: 'Token de acesso requerido'
      })
    }

    const token = authHeader.substring(7)

    // Decode and validate token using adapter
    const user = await adapter.adaptTokenToReqUser(token)

    // Check if token is in denylist (logged out)
    const isValid = await adapter.isTokenValid(user.jti)

    if (!isValid) {
      return res.status(401).json({
        error: 'Token foi invalidado'
      })
    }

    // Attach user to request
    ;(req as any).user = user

    next()
  } catch (error: any) {
    console.error('Middleware authentication error:', error)
    return res.status(401).json({
      error: 'Token inválido ou expirado'
    })
  }
}
